<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.abdallah</groupId>
  <artifactId>SpringConfigDemo</artifactId>
  <version>1.0</version>
  <packaging>jar</packaging>

  <name>SpringConfigDemo</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

    <dependencies>

        <!-- Spring Context
             دي أهم dependency عندنا لأننا هنستخدم
             ApplicationContext والـ Java Configuration
        -->
        <dependency>

            <groupId>org.springframework</groupId>

            <artifactId>spring-context</artifactId>

            <version>6.2.9</version>

        </dependency>

    </dependencies>

</project>
